wml_credentials:
  # username and password can be replaced by user token
  username: jbtang@au1.ibm.com
  password: workharder17Tjb
  instance_id: openshift
  url: https://dse-cpd35-wapi.cpolab.ibm.com/
  version: '3.5'

prj_info:
  code_dir: ../code_example_to_be_deployed
  main_file: main_no_email.py

deployment_info:
  function_name: code_example_to_be_deployed
  space_id: 93b173af-05df-452f-9e68-bba14c70eb1d

  # True: replace deployment if same deployment name has been found
  # False: quit the deployment if same deployment name has been found
  force_2_update: True   # default value: False

  # online: online API
  # batch_job: scheduled upon requests
  deploy_mode: batch_job  # default value: batch_job

  # hardware spec: refer to:https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/deploy-batch-details.html
  # Size 	Hardware definition
  # XS 	1 CPU and 4 GB RAM
  # S 	2 CPU and 8 GB RAM
  # M 	4 CPU and 16 GB RAM
  # ML 	4 CPU and 32 GB RAM
  # L 	8 CPU and 32 GB RAM
  # XL 	16 CPU and 64 GB RAM
  hardware_spec: S

 num_nodes: 1

  #For cpd3.5
  runtime: default_py3.7

# leave empty or setting "False" if not want to send email
email_setting:
  send_email_when_successful: True # True, False
  send_email_when_fail: True # True, False
  smtp_server: ap.relay.ibm.com
  sender: jbtang@au1.ibm.com
  receivers: ['jbtang@au1.ibm.com', 'bennytang2008@gmail.com']


