wml_credentials:
  # username and password can be replaced by user token
  username: jbtang@au1.ibm.com
  password: workharder17Tjb
  instance_id: openshift
  url: https://dse-cpd40-cluster1.cpolab.ibm.com
  version: '4.0'

prj_info:
  code_dir: /Users/jbtang/projects/cpd45_dse_deploy/assets/code
  main_file: sqlserver_connection.py

deployment_info:
  function_name: sqlserver_connection
  space_id: 7a81cf6f-2d28-45a0-82a9-b30cb05438d9

  # True: replace deployment if same deployment name has been found
  # False: quit the deployment if same deployment name has been found
  force_2_update: True   # default value: False

  # online: online API
  # batch_job: scheduled upon requests
  deploy_mode: batch_job  # default value: batch_job

  # hardware spec: refer to:https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/deploy-batch-details.html
  # Size 	Hardware definition
  # XS 	1 CPU and 4 GB RAM
  # S 	2 CPU and 8 GB RAM
  # M 	4 CPU and 16 GB RAM
  # ML 	4 CPU and 32 GB RAM
  # L 	8 CPU and 32 GB RAM
  # XL 	16 CPU and 64 GB RAM
  hardware_spec: S

  num_nodes: 1

  #For cpd4.0
  runtime: 'runtime-22.1-py3.9'

# leave empty or setting "False" if not want to send email
email_setting:
  send_email_when_successful: True # True, False
  send_email_when_fail: True # True, False
  smtp_server: ap.relay.ibm.com
  sender: jbtang@au1.ibm.com
  receivers: ['jbtang@au1.ibm.com', 'bennytang2008@gmail.com']


